# Generated by Django 5.1.4 on 2024-12-16 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_code", models.CharField(max_length=10, unique=True)),
                ("name", models.URLField(blank=True, null=True)),
                ("ios_url", models.URLField(blank=True, null=True)),
                ("android_url", models.URLField(blank=True, null=True)),
                ("i_pad_url", models.URLField(blank=True, null=True)),
                ("non_google_huawei_url", models.URLField(blank=True, null=True)),
                ("fallback_url", models.URLField(blank=True, null=True)),
                ("click_count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClickStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("os_family", models.CharField(blank=True, max_length=50, null=True)),
                ("browser", models.CharField(blank=True, max_length=50, null=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("utm_source", models.CharField(blank=True, max_length=100, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "short_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="links.shortlink",
                    ),
                ),
            ],
        ),
    ]
